/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.73
 * Generated at: 2021-12-08 03:48:08 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.views.member;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class myPage_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("	");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "../common/header.jsp", out, false);
      out.write("\r\n");
      out.write("	\r\n");
      out.write("	\r\n");
      out.write("	<div class=\"container\"  style=\"min-height:700px\">\r\n");
      out.write("		\r\n");
      out.write("		<div class=\"row my-5\">\r\n");
      out.write("		\r\n");
      out.write("			");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "sideMenu.jsp", out, false);
      out.write("		\r\n");
      out.write("				\r\n");
      out.write("			<div class=\"col-sm-8\">\r\n");
      out.write("				<h3>My Page</h3>\r\n");
      out.write("				<hr>\r\n");
      out.write("				<div class=\"bg-white rounded shadow-sm container p-3\">\r\n");
      out.write("					<form method=\"POST\" action=\"update\" onsubmit=\"return memberUpdateValidate();\" class=\"form-horizontal\" role=\"form\">\r\n");
      out.write("						<!-- 아이디 -->\r\n");
      out.write("						<div class=\"row mb-3 form-row\">\r\n");
      out.write("							<div class=\"col-md-3\">\r\n");
      out.write("								<h6>아이디</h6>\r\n");
      out.write("							</div>\r\n");
      out.write("							<div class=\"col-md-6\">\r\n");
      out.write("								<h5 id=\"id\"> ");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${sessionScope.loginMember.memberId }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write(" </h5>\r\n");
      out.write("							</div>\r\n");
      out.write("						</div>\r\n");
      out.write("	\r\n");
      out.write("						<!-- 이름 -->\r\n");
      out.write("						<div class=\"row mb-3 form-row\">\r\n");
      out.write("							<div class=\"col-md-3\">\r\n");
      out.write("								<h6>이름</h6>\r\n");
      out.write("							</div>\r\n");
      out.write("							<div class=\"col-md-6\">\r\n");
      out.write("								<h5 id=\"name\">");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${loginMember.memberName}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("</h5>\r\n");
      out.write("							</div>\r\n");
      out.write("						</div>\r\n");
      out.write("	\r\n");
      out.write("						<!-- 전화번호 -->\r\n");
      out.write("						<div class=\"row mb-3 form-row\">\r\n");
      out.write("							<div class=\"col-md-3\">\r\n");
      out.write("								<label for=\"phone1\">전화번호</label>\r\n");
      out.write("							</div>\r\n");
      out.write("							<!-- 전화번호1 -->\r\n");
      out.write("							<div class=\"col-md-3\">\r\n");
      out.write("								<select class=\"custom-select\" id=\"phone1\" name=\"phone\">\r\n");
      out.write("									<option>010</option>\r\n");
      out.write("									<option>011</option>\r\n");
      out.write("									<option>016</option>\r\n");
      out.write("									<option>017</option>\r\n");
      out.write("									<option>019</option>\r\n");
      out.write("								</select>\r\n");
      out.write("							</div>\r\n");
      out.write("							\r\n");
      out.write("	\r\n");
      out.write("							<!-- 전화번호2 -->\r\n");
      out.write("							<div class=\"col-md-3\">\r\n");
      out.write("								<input type=\"number\" class=\"form-control phone\" id=\"phone2\" name=\"phone\" value=\" \">\r\n");
      out.write("							</div>\r\n");
      out.write("	\r\n");
      out.write("							<!-- 전화번호3 -->\r\n");
      out.write("							<div class=\"col-md-3\">\r\n");
      out.write("								<input type=\"number\" class=\"form-control phone\" id=\"phone3\" name=\"phone\" value=\" \">\r\n");
      out.write("							</div>\r\n");
      out.write("						</div>\r\n");
      out.write("	\r\n");
      out.write("						<!-- 이메일 -->\r\n");
      out.write("						<div class=\"row mb-3 form-row\">\r\n");
      out.write("							<div class=\"col-md-3\">\r\n");
      out.write("								<label for=\"memberEmail\">Email</label>\r\n");
      out.write("							</div>\r\n");
      out.write("							<div class=\"col-md-6\">\r\n");
      out.write("								<input type=\"email\" class=\"form-control\" id=\"email\" name=\"email\" value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${loginMember.memberEmail}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\">\r\n");
      out.write("							</div>\r\n");
      out.write("						</div>\r\n");
      out.write("						<br>\r\n");
      out.write("	\r\n");
      out.write("						<!-- 주소 -->\r\n");
      out.write("						<!-- 오픈소스 도로명 주소 API -->\r\n");
      out.write("						<!-- https://www.poesis.org/postcodify/ -->\r\n");
      out.write("						<div class=\"row mb-3 form-row\">\r\n");
      out.write("							<div class=\"col-md-3\">\r\n");
      out.write("								<label for=\"postcodify_search_button\">우편번호</label>\r\n");
      out.write("							</div>\r\n");
      out.write("							<div class=\"col-md-3\">\r\n");
      out.write("								<input type=\"text\" name=\"address\" class=\"form-control postcodify_postcode5\" value=\" \">\r\n");
      out.write("							</div>\r\n");
      out.write("							<div class=\"col-md-3\">\r\n");
      out.write("								<button type=\"button\" class=\"btn btn-primary\" id=\"postcodify_search_button\">검색</button>\r\n");
      out.write("							</div>\r\n");
      out.write("						</div>\r\n");
      out.write("	\r\n");
      out.write("						<div class=\"row mb-3 form-row\">\r\n");
      out.write("							<div class=\"col-md-3\">\r\n");
      out.write("								<label for=\"address1\">도로명 주소</label>\r\n");
      out.write("							</div>\r\n");
      out.write("							<div class=\"col-md-9\">\r\n");
      out.write("								<input type=\"text\" class=\"form-control postcodify_address\" name=\"address\" id=\"address1\"  value=\" \">\r\n");
      out.write("							</div>\r\n");
      out.write("						</div>\r\n");
      out.write("	\r\n");
      out.write("						<div class=\"row mb-3 form-row\">\r\n");
      out.write("							<div class=\"col-md-3\">\r\n");
      out.write("								<label for=\"address2\">상세주소</label>\r\n");
      out.write("							</div>\r\n");
      out.write("							<div class=\"col-md-9\">\r\n");
      out.write("								<input type=\"text\" class=\"form-control postcodify_details\" name=\"address\" id=\"address2\"  value=\" \">\r\n");
      out.write("							</div>\r\n");
      out.write("						</div>\r\n");
      out.write("	\r\n");
      out.write("						<hr class=\"mb-4\">\r\n");
      out.write("						<button class=\"btn btn-primary btn-lg btn-block\" type=\"submit\">수정</button>\r\n");
      out.write("					</form>\r\n");
      out.write("				</div>\r\n");
      out.write("			</div>\r\n");
      out.write("		</div>\r\n");
      out.write("	</div>\r\n");
      out.write("	<br><br>\r\n");
      out.write("	\r\n");
      out.write("	");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "../common/footer.jsp", out, false);
      out.write("\r\n");
      out.write("		\r\n");
      out.write("		\r\n");
      out.write("	<!-- 오픈소스 도로명 주소 검색 API -->\r\n");
      out.write("	<!-- https://www.poesis.org/postcodify/ -->\r\n");
      out.write("	<!-- postcodify 라이브러리를 CDN 방식으로 추가. -->\r\n");
      out.write("	<script src=\"//d1p7wdleee1q2z.cloudfront.net/post/search.min.js\"></script>\r\n");
      out.write("	<script>\r\n");
      out.write("		// 검색 단추를 누르면 팝업 레이어가 열리도록 설정한다.\r\n");
      out.write("		$(function () {\r\n");
      out.write("			$(\"#postcodify_search_button\").postcodifyPopUp();\r\n");
      out.write("		});\r\n");
      out.write("	</script>\r\n");
      out.write("	\r\n");
      out.write("	\r\n");
      out.write("	\r\n");
      out.write("	\r\n");
      out.write("</body>\r\n");
      out.write("</html>\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
